version: '3.3'
services:
  api:
    image: perry-the-platypus
    command:
      - cd /home/api && yarn dev
    ports:
      - 8000:80
    restart: on-failure
    volumes:
      - ./api:/home/api
    environment:
      - NODE_ENV=development
      - PORT=80
    depends_on:
      - database

  web:
    image: perry-the-platypus
    command:
      - cd /home/web && yarn serve
    ports:
      - 3000:8080
    restart: on-failure
    volumes:
      - ./web:/home/web
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  database:
    image: mariadb:latest
    restart: always
    environment:
    - MYSQL_DATABASE=perry
    - MYSQL_ROOT_PASSWORD=ultrasecretpassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - database