version: '3.3'
services:
  database:
    image: mariadb:latest
    environment:
    - MYSQL_ROOT_PASSWORD=ultrasecretpassword
    - MYSQL_DATABASE=perry

  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - database

  api:
    image: perry-the-platypus
    command:
      - cd /home/api && yarn dev
    ports:
      - 8000:80
    volumes:
      - ./api:/home/api
    environment:
      - NODE_ENV=development
      - PORT=80
    depends_on:
      - database

  web:
    image: perry-the-platypus
    command:
      - cd /home/web && yarn serve
    ports:
      - 3000:8080
    volumes:
      - ./web:/home/web
    environment:
      - NODE_ENV=development
    depends_on:
      - api