const { constants, endpoints } = require("./constants/payment-method-config");
const PROTOCOL = constants.PS_REQUEST_PROTOCOL;
const HOST = constants.PS_REQUEST_HOST;

/**
 * Get the notifications API's complete URL
 *
 * @param {String} notificationCode - The code of the notification received by the system
 * @param {Object} authParams - Params used for gateway authentication
 * @param {String} authParams.email - Seller's email address (must be the same of the seller's account on the gateway)
 * @param {String} authParams.token - Seller's token (generated by the gateway)
 */
const getNotificationApiURL = notificationCode => {
  return `${getEndpointApiURL(
    endpoints.notifications
  )}/${notificationCode}?email=${process.env.PS_SELLER_EMAIL}&token=${
    process.env.PS_SELLER_TOKEN
  }`;
};

/**
 * Get the base API URL
 * @param {boolean} ws - Whether do you want or not 'ws.' at the beginning of the URL
 */
const getBaseApiURL = ws => `${PROTOCOL}://${ws ? "ws." + HOST : HOST}`;

/**
 * Get the endpoint (passed by param) API's complete URL
 *
 * @param {String} endpoint - The endpoint
 */
const getEndpointApiURL = endpoint => `${getBaseApiURL(true)}/${endpoint}`;

const utils = { getBaseApiURL, getNotificationApiURL };

module.exports = utils;
